a = (input('digite qualquer coisa:'))
print('o tipo primitivo desse valor é:',type(a))
print('tem números e letras?:',a.isalnum())
print('Só tem letras?:',a.isalpha())
print('é um titulo?:',a.istitle())
print('Só tem número?:',a.isnumeric())
print('Só tem espaços?:',a.isspace())
print('tem apenas letras maiusculas?:',a.isupper())
print('tem apenas letras minusculas?:',a.islower())
print('Esta capitalizada?:',a.istitle())